apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-test1apps
  namespace: argocd
  
spec:
  project: default
  
  source:
    repoURL: https://github.com/sivaraam73/argocd-test1.git
    targetRevision: HEAD
    path: apps
    
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  syncPolicy:
    syncOptions:
      - CreateNamespace = true
    
    automated:
      selfHeal: true
      prune: true
      